# Table of Contents

[N Queens](#N-Queens)  
[Knight Moves](#Knight-Moves)  
[subsets](#Subsets)

# N Queens
[Video reference](https://youtu.be/CQ3nDMcchdA)

In [3]:
import numpy as np
board = np.zeros((4, 4))
def validate(board, n):
    for row in range(0, n):
        if sum(board[row,]) > 1:
            return False
    for col in range(0, n):
        if sum(board[:, col]) > 1:
            return False
    diags = [board[::-1].diagonal(i) for i in range(-(n - 1), n)]  # parallel to main diag of b (bottom left to top right)
    diags.extend([board.diagonal(i) for i in range((n - 1), -n, -1)]) # perpendicular to main diag
    for diag in diags:
        if len(diag) > 1:
            if sum(diag) > 1:
                return False
    return True

def place(board, col, n):
    if validate(board, n):
        if board.sum() == n:
            return True
        for row in range(0, n):
            board[row, col] = 1
            if validate(board,n):
                if place(board, col + 1, n):
                    return True
                board[row, col] = 0
            else:
                board[row, col] = 0
    return False
if place(board, 0, 4):
    print(board)

[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]


In [4]:
 import numpy as np
 a=np.arange(9).reshape(3,3)
 print("original matrix is :\n",a)
 m=np.trace(a) # sum of main diag
 print("trace of matrix :", m)

original matrix is :
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
trace of matrix : 12


In [5]:
b = np.arange(0,25).reshape(5,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [6]:
np.trace(b)

60

In [7]:
m = b.diagonal()                                     
print("diagonal elements \n:", m)

diagonal elements 
: [ 0  6 12 18 24]


In [8]:
b[::-1]

array([[20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [9]:
b[::-1].diagonal(-2)

array([10,  6,  2])

In [10]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [11]:
b[::-1,:]

array([[20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [12]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [13]:
n = 5
diags = [b[::-1].diagonal(i) for i in range(-(n - 1), n)] # parallel to main diag of b (bottom left to top right)
k = [b.diagonal(i) for i in range((n - 1), -n, -1)] # perpendicular to main diag
diags.extend(k)
diags

[array([0]),
 array([5, 1]),
 array([10,  6,  2]),
 array([15, 11,  7,  3]),
 array([20, 16, 12,  8,  4]),
 array([21, 17, 13,  9]),
 array([22, 18, 14]),
 array([23, 19]),
 array([24]),
 array([4]),
 array([3, 9]),
 array([ 2,  8, 14]),
 array([ 1,  7, 13, 19]),
 array([ 0,  6, 12, 18, 24]),
 array([ 5, 11, 17, 23]),
 array([10, 16, 22]),
 array([15, 21]),
 array([20])]

In [14]:
k = [b.diagonal(i) for i in range((n - 1), -n, -1)]
k

[array([4]),
 array([3, 9]),
 array([ 2,  8, 14]),
 array([ 1,  7, 13, 19]),
 array([ 0,  6, 12, 18, 24]),
 array([ 5, 11, 17, 23]),
 array([10, 16, 22]),
 array([15, 21]),
 array([20])]

In [15]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# Knight Moves
[Video reference](https://youtu.be/CQ3nDMcchdA)

In [ ]:
import numpy as np
def validate(board, row, col):
    if row >= 0 and row < 8 and col >= 0 and col < 8 and board[row, col]== 0:
        return True

def place(board, row, col, n, counter):
    # from tutorial
    #move_x = [2, 1, -1, -2, -2, -1, 1, 2]
    #move_y = [1, 2, 2, 1, -1, -2, -2, -1]

    move_row = [-2, -1, 1, 2, 2, 1, -1, -2]
    move_col = [1, 2, 2, 1, -1, -2, -2, -1]

    for i in range(8):
        if counter > 64:
            return True

        new_row = row + move_row[i]
        new_col = col + move_col[i]
        if validate(board, new_row, new_col):
            board[new_row, new_col] = counter
            if place(board, new_row, new_col, n, counter + 1):
                return True
            board[new_row, new_col] = 0
    return False

board = np.zeros((8, 8))
board[3, 2] = 1
if place(board, 3, 2, 8, 2):
    print(board.sum())
    print(board)

# Subsets  
Time Complexity: O(n * 2^n)  
There are 2^n total subsets where n is the number of elements in the original list.  
Every subset , in the worst case, can have upto n elements. Elements are added one at a time.    
[Video reference](https://youtu.be/REOH22Xwdkk)

In [2]:
def subsets(nums):
    res = []
    subset = []
    def dfs(i): # depth first search

        # base case
        if i >= len(nums):
            # copy because subset will be modified which will affect any reference to the subset
            res.append(subset.copy())
            return # return to the prev depth in the tree  3(past the leaf nodes) >> 2(leaf nodes) >> 1
        # for the left side of every node
        subset.append(nums[i])
        dfs(i + 1)
        # right side of every node
        subset.pop() # value of previous node before branching
        dfs(i + 1) # branch to the right

    dfs(0)
    return res

print(subsets([1,2,3]))

[[1, 2, 3], [1, 2], [1, 3], [1], [2, 3], [2], [3], []]
